name: Deploy to Azure Web App

on:
  push:
    branches:
      - main  # or your default branch name

env:
  AZURE_WEBAPP_NAME: festa-design-test    # Updated Web App name
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '18.x'
  PHP_VERSION: '8.2'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.PHP_VERSION }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
        coverage: none

    - name: Install Composer Dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Install NPM Dependencies
      run: npm install

    - name: Build Assets
      run: npm run build

    - name: Create .env file
      run: |
        echo 'APP_NAME="Festa Design"' > .env
        echo 'APP_ENV=production' >> .env
        echo 'APP_KEY=${{ secrets.APP_KEY }}' >> .env
        echo 'APP_DEBUG=false' >> .env
        echo 'APP_URL=https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net' >> .env
        echo 'LOG_CHANNEL=stack' >> .env
        echo 'DB_CONNECTION=sqlite' >> .env
        echo 'SESSION_DRIVER=file' >> .env
        echo 'CACHE_DRIVER=file' >> .env
        echo 'QUEUE_CONNECTION=sync' >> .env

    - name: Run Database Migrations
      run: php artisan migrate --force

    - name: Optimize Laravel
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} 